Security Updates Mar, 22 2025
- Update nginx: 1.27.3 ==> 1.27.4
- Change mysql bind address: 0.0.0.0 ==> 127.0.0.1
- Delete phpinfo.php from site root
- Update PHP  to 8.4.5
- Update xdebug to 3.4.2
- Disable http 80 port by default
- Change mysqld init passwd length to 32

diff --git a/qweb b/qweb
--- a/qweb
+++ b/qweb
@@ -6,8 +6,14 @@ SCRIPT_ROOT=$(cd "$SCRIPT_ROOT" && pwd -P)
 if hash pwsh 2>/dev/null; then
     POWERSHELL=pwsh
 else
-    echo "PowerShell 7+ required."
-    exit 1
+    sudo apt update
+    sudo snap install powershell --classic
+    if hash pwsh 2>/dev/null; then
+        POWERSHELL=pwsh
+    else
+        echo "PowerShell 7+ required."
+        exit 1
+    fi
 fi
 
 $POWERSHELL "$SCRIPT_ROOT/qweb.ps1" "$@"
